### PR TITLE
Fix remote script argument parsing issue.

### LINKED ISSUE #83: "Test events were not received" in Android Studio Artic Fox
After migrating to [Android Studio Artic Fox](https://developer.android.com/studio), when running unit tests from the IDE, it says "Test events were not received"

image

Here is the output:
```
Executing tasks: [:app:cleanTestDebugUnitTest, :app:testDebugUnitTest] in project /Users/gmerino/Workspace/personal/TestsInRemote


> Configure project :
Here's Mirakle 1.4.3. All tasks will be executed on arc-prod-1.tuenti.io.
> Task :uploadToRemote
> Task :executeOnRemote
> Task :app:cleanTestDebugUnitTest
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :app:processDebugMainManifest UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugManifestForPackage UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :app:compileDebugKotlin
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:compileDebugJavaWithJavac UP-TO-DATE
> Task :app:bundleDebugClasses UP-TO-DATE
> Task :app:compileDebugUnitTestKotlin
> Task :app:preDebugUnitTestBuild UP-TO-DATE
> Task :app:javaPreCompileDebugUnitTest UP-TO-DATE
> Task :app:compileDebugUnitTestJavaWithJavac NO-SOURCE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:processDebugUnitTestJavaRes NO-SOURCE
> Task :app:testDebugUnitTest
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 2s
18 actionable tasks: 4 executed, 14 up-to-date
> Task :downloadInParallel
> Task :downloadFromRemote
> Task :mirakle
Total time : 5.592 secs
Task uploadToRemote took : 0.316 secs
Task executeOnRemote took : 3.027 secs
Task downloadFromRemote took : 0.393 secs
5 actionable tasks: 5 executed
10:06:51: Tasks execution finished ':app:cleanTestDebugUnitTest :app:testDebugUnitTest --tests "com.gmerino.testsinremote.ExampleUnitTest"'.
```
I've tried with different versions of Gradle and also use Junit4 & Junit5, but I wasn't able to find a workaround

**Steps to reproduce**
Create an empty project in Android Studio, it will create a class called ExampleUnitTest. Try executing that test when mirakle is configured.

**IntelliJ**
I've also reproduced it in IntelliJ IDEA 2021.2.1 with the same STRs

### PR DESCRIPTION
**Pull request by JSpiner**
## Summary
- Fix argument parsing issue in 'executeOnRemote'
- Fix #83 #110 

## Description
In previous versions, executeOnRemote run likes below
```bash
$ ssh mainframer "~/mirakle/my_project/gradlew" -Pmirakle.build.on.remote=true -p "~/mirakle/my_project" \
":home:testDebugUnitTest" --continue --parallel --configure-on-demand --project-prop \ 
"android.injected.enableStableIds=true" --project-prop "android.injected.build.density=420dpi" --project-prop \
"android.injected.build.api=31" --project-prop "android.injected.invoked.from.ide=true" --project-prop \
"android.injected.build.abi=arm64-v8a,armeabi-v7a,armeabi" \
--project-prop "android.injected.studio.version=2021.2.1 Patch 1" --system-prop "idea.active=true" --system-prop \
"idea.version=2021.2" --stacktrace
```

It seems to work, but it doesn't.
Because gradle Exec mainpulates args. (It seems to change the quotes appropriately.)
It would be helpful if we could see how the script that mirakle runs with gradle Exec is actually passed.
However, looking at the [gradle source](https://github.com/gradle/gradle/blob/55ebbdcbff8a379f2afe0394e8d68583a0c471e3/subprojects/core/src/main/java/org/gradle/api/tasks/AbstractExecTask.java#L80), it is too abstract and difficult to find out how it works, and logging in the ssh server did not work well.

So, my idea is to separate only the remote script part with `'`.
If we pass the remote script as a string, I think there is no need for additional string quote wrapping(`"`).
Like below
```bash
$ ssh mainframer '{remote script}'
```

## Changes
- remove `"` quotes in args.
- wrap remote args to one string.
    - It seems that gradle automatically wraps it without adding `'`.

### CODE REVIEW

**Comment by JSpiner** [comment]
@Adambl4 
Hi, I fixed issue that ide cannot found tests(https://github.com/Adambl4/mirakle/issues/83). Can you review it?

**Comment by skrugly** [comment]
Hey @JSpiner, it seems it dosent work on some of my test cases.
For example running such command from #102 makes mirakle fail
```
 ./gradlew testDebugUnitTest --tests "MyUnitTestClass.testFunction haha"
```

**Comment by skrugly** [comment]
And I can't find where you are wrapping remote command in single quote, could you point me please.

**Comment by JSpiner** [comment]
https://github.com/Adambl4/mirakle/commit/eba87d1f202fbf05e96d85bf7319d88405feb63b#diff-5c5f3cc932f8a1ca09848c5c2466a8ce3872748600b75821773c3cedfb0e78b8R386

```kotlin
val remoteBashCommand = "echo 'set -e && cd \"${config.remoteFolder}/${gradlewRoot.name}\" && $remoteGradleCommand' | bash"
...
args(remoteBashCommand)
```

This is same with what I want to do.
It already merged in a different way, so I will close this PR.
But there is another issue in 1.5.2. I made a separate PR, so please review it.

https://github.com/Adambl4/mirakle/pull/123

**Pull request closed without merging**
