### PR TITLE
Add support for dependency verification start params

### PR DESCRIPTION
**Pull request by nesterov-n**
Gradle offers useful feature: [dependency verification](https://docs.gradle.org/current/userguide/dependency_verification.html) 

It writes sha256 checksum and pgp signature in `$PROJECT_ROOT/gradle/verification-metadata.xml`. After that every build fails if checksum or signature of dependency differs. 

This PR adds support for start params related to dependency verification: 
`--write-verification-metadata sha256|pgp`
and 
`-dependency-verification strict|lenient|off`

### CODE REVIEW

**Comment by skrugly** [comment]
Hey, this looks great, thanks for the PR.
I will upload an RC of mirakle and would like to ask you to test it soon.

**Comment by skrugly** [comment]
Could you check `io.github.adambl4:mirakle:1.5.3-RC-5` and let me know does it work as expected.

**Comment by nesterov-n** [comment]
Checked RC-5. Unexpectedly, it doesn't work properly. 
I think  https://github.com/Adambl4/mirakle/pull/119 might affects dependency verification params. I'll take a look in a few days.

**Comment by nesterov-n** [comment]
My bad.  `--write-verification-metadata sha256` must be passed as list, not as String.
Fixed at  https://github.com/Adambl4/mirakle/pull/120

**Comment by skrugly** [comment]
Check please  `io.github.adambl4:mirakle:1.5.3-RC-7`

**Comment by nesterov-n** [comment]
1.5.3-RC-7 works fine. Thanks

**Pull request merged**
